### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by tom967** [patrickkfkan/volumio-jellyfin#1]
Hi ! Thanks for the great idea.

I encounter this when I try to install on Volumio 2.853 + Jellyfin 10.6.4:

volumio@sam:~/jellyfin-plugin/volumio-jellyfin$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Télécharger le plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip
Progress: 30
Status :Création de l'emplacement de destination
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>Création de l'emplacement de destination
Progress: 40
Status :Décompression du plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>Création de l'emplacement de destination<br>Décompression du plugin
Progress: 50
Status :Vérification des doublons
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>Création de l'emplacement de destination<br>Décompression du plugin<br>Vérification des doublons
Progress: 60
Status :Copie du plugin à destination
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>Création de l'emplacement de destination<br>Décompression du plugin<br>Vérification des doublons<br>Copie du plugin à destination
Progress: 70
Status :Installation des utilitaires nécessaires
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>Création de l'emplacement de destination<br>Décompression du plugin<br>Vérification des doublons<br>Copie du plugin à destination<br>Installation des utilitaires nécessaires
Progress: 0
Status :Une erreur est survenue lors de l'installation du plugin Error
Downloading plugin at http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/jellyfin.zip<br>Création de l'emplacement de destination<br>Décompression du plugin<br>Vérification des doublons<br>Copie du plugin à destination<br>Installation des utilitaires nécessaires<br>Une erreur est survenue lors de l'installation du plugin Error

But I can still see the plugin in Volumio's interface. And activate it. I can add my Jellyfin server but the data is not flowing, nothing appears.

UPDATE : after a few minutes, data's been flowing nicely. Everything seems in order. Thank you so much !

**Comment by patrickkfkan** [comment]
Hello,

I have tested this on both a Raspberry Pi 3 and x86 computer running the same versions of Volumio and Jellyfin (both fresh installs). I got no errors with 'volumio plugin install".  What device are you using? 

After adding the server, does the server appear at all when you click "Jellyfin"? 

Could you SSH into Volumio and check the logs for possible errors? You can search for the following text:

>[jellyfin-poller-worker] _doPoll(): Polling <your server address>

Check the lines that follow and see if there are messages relating to connection errors.  You can paste those lines here but I would suggest you hide the address of your server first.

-Patrick

**Comment by patrickkfkan** [comment]
Ahh, sorry,  I left the reply screen idling for a while before submitting it and didn't realize you already closed the issue.

**Comment by tom967** [comment]
I have the same setup : Raspberry Pi 3 and x86 server. Awesome plugin !
