### ISSUE TITLE
Plugin does not expose content being played to Jellyfin

### ISSUE THREAD

**Issue by captainnapalm** [patrickkfkan/volumio-jellyfin#4]
First off, thanks for the awesome plugin. I'm wondering if it's possible to expose the artist/track metadata to Jellyfin when playing content. My use case is that I use multi-scrobbler to manage scrobbling to Last.fm, Listenbrainz, and maloja, and currently this works for all clients I've used Jellyfin with as they expose to Jellyfin what is being played (e.g. Symfonium on Android, sonixd on PC). The exception is this volumio plugin which just shows an active session to Jellyfin, but does not tell Jellyfin what content is being accessed/played.

**Comment by patrickkfkan** [comment]
I'll see what can be done. First I have to get my Jellyfin server back up and running :laughing:

**Comment by captainnapalm** [comment]
That would be appreciated. 

For context, I'm running the latest version of each software. Jellyfin 10.8.9 and Volumio 3.449.

**Comment by captainnapalm** [comment]
From my quick test (tested one song on one player) it seems to be reporting the content correctly to Jellyfin and multi-scrobbler picked it up to scrobble to last.fm successfully!

**Comment by patrickkfkan** [comment]
Good to know. I'll close this issue for now.
