### ISSUE TITLE
Error when the jellyfin server is listening on a subpath

### ISSUE THREAD

**Issue by oscmedgon** [patrickkfkan/volumio-jellyfin#8]
I'm encountering an error when using the plugin:
My environment is:
- Jellyfin server v10.9.10 listening on http://server_ip:server_port/jelly
- Volumio v3.742  with plugin v1.1.1 on a different device pointing to the jellyfin base path (http://server_ip:server_port/jelly)

# Expected behavior
When playing music the audio streams are requested to the Jellyfin server on the specified path.

# Current behavior
The music stream URL does not contain the path leading to an error in the playback.

The received error in the WS is (The original error shows the IP and port but have ben replaced to report the issue):
```
42["pushToastMessage",{"type":"error","title":"Error","message":"Failed to decode http://server_ip:server_port/Audio/song_id/stream.flac?static=true&mediaSourceId=song_id&t.flac"}]
```
Updating the shown URL by adding the path leads to the actual stream which works.

**Comment by patrickkfkan** [comment]
Updated v1.1.2 which should fix this. Currently in beta channel. To install:

- Uninstall current version.
- Enable Plugins Test Mode in `http://<volumio address>/dev`
- Find the Jellyfin plugin in the plugin store. Click the Details button under it and choose latest beta version to install.
- Restart Volumio.

(All steps mandatory)
